# Generated by Django 3.2 on 2022-11-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20221025_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
